#!/bin/bash
# ----------------------------------------------------------------------------------------------
# FWIFI is a powerful wireless security testing toolkit designed for educational and authorized
# testing purposes. It provides a collection of essential tools for assessing and securing Wi-Fi
# networks.
# ----------------------------------------------------------------------------------------------
# WARNING: This script is designed exclusively for educational and authorized testing purposes.
# Unauthorized access to networks or systems is strictly prohibited. Users must adhere to local
# laws and regulations. The author is not liable for any misuse or damage caused by this script.
# By using FWIFI, you acknowledge and agree to these terms.
# ----------------------------------------------------------------------------------------------

# Function to display intro text with typing effect
display_intro() {
    local intro_text=(
        "FWIFI is a powerful wireless security testing toolkit designed for educational and authorized "
        "testing purposes. It provides a collection of essential tools for assessing and securing Wi-Fi"
        "networks."
        ""
        "WARNING: This script is designed exclusively for educational and authorized testing purposes. "
        "Unauthorized access to networks or systems is strictly prohibited. Users must adhere to local "
        "laws and regulations. The author is not liable for any misuse or damage caused by this script."
        "By using FWIFI, you acknowledge and agree to these terms."
        ""
    )

    for line in "${intro_text[@]}"; do
        type_effect "$line" 0.1
    done
}

# Function for typing effect
type_effect() {
    local text="$1"
    local delay="$2"

    for ((i = 0; i < ${#text}; i++)); do
        echo -n "${text:$i:1}"
        sleep "$delay"
    done
    echo ""
}

# Function for main menu
main_menu() {
    echo ""
    echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    echo "  _______      ________      _______      _______      _______  "
    echo " |    ___|    |  |  |  |    |_     _|    |    ___|    |_     _| "
    echo " |    ___|    |  |  |  |     _|   |_     |    ___|     _|   |_  "
    echo " |___|        |________|    |_______|    |___|        |_______| "
    echo "                                                                "
    echo "          Github: https://github.com/rofidoang03/fwifi          "
    echo "                                                                "
    echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    echo "                                                                "
    echo " [Menu] FWIFI                                                   "
    echo "                                                                "
    echo " [0] Update                                                     "
    echo " [1] Enable Monitor Mode                                        "
    echo " [2] Disable Monitor Mode                                       "
    echo " [3] Capture Wi-Fi Data                                         "
    echo " [4] Inject Wi-Fi Packets                                       "
    echo " [5] Check for valid 4-way frames                               "
    echo " [6] Crack Wi-Fi Key                                            "
    echo "[99] Exit                                                       "
    echo "                                                                "
    # Prompt user input
    read -p "[fwifi] " choice

    case $choice in
        0) update_system ;;
        1) enable_monitor_mode ;;
        2) disable_monitor_mode ;;
        3) capture_wifi_data ;;
        4) inject_wifi_packets ;;
        5) check_4way_frames ;;
        6) crack_wifi_key ;;
        99) exit_program ;;
        ls) list_files ;;
        *) invalid_choice ;;
    esac
}

# Function to update system packages
update_system() {
    echo ""
    apt-get update -y
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to enable monitor mode
enable_monitor_mode() {
    echo ""
    airmon-ng check kill
    airmon-ng start "${interface}"
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to disable monitor mode
disable_monitor_mode() {
    echo ""
    airmon-ng stop "${interface}"
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to capture Wi-Fi data
capture_wifi_data() {
    echo ""
    echo "[Menu] Choose Wi-Fi Data Capture Tool"
    echo ""
    echo "[1] Airodump-ng"
    echo "[2] Besside-ng"
    echo ""

    while true; do
        read -p "[fwifi] Enter your choice (1-2): " capture_tool

        case "${capture_tool}" in
            1) airodump_capture ;;
            2) besside_capture ;;
            *) echo "[Error] Invalid choice." ;;
        esac
    done
}

# Function to capture Wi-Fi data using Airodump-ng
airodump_capture() {
    airodump-ng "${interface}"
    echo ""

    read -p "[fwifi] Enter the BSSID you want to attack:: " target_bssid

    if [[ ! "${target_bssid}" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
        echo "[Error] Invalid BSSID format. Please enter a valid MAC address (e.g., XX:XX:XX:XX:XX:XX)."
    else
        read -p "[fwifi] Enter the channel: " channel

        if [[ ! "$channel" =~ ^[0-9]+$ ]]; then
            echo "[Error] Invalid channel. Please enter a valid numeric channel."
        else
            read -p "[fwifi] Enter the output file name: " output_file
            airodump-ng --bssid "${target_bssid}" --channel "${channel}" -w "${output_file}" "${interface}"
            echo ""
            read -p "[Info] Press [Enter] to continue..."
        fi
    fi
}

# Function to capture Wi-Fi data using Besside-ng
besside_capture() {
    airodump-ng "${interface}"
    echo ""

    read -p "[fwifi] Enter the BSSID you want to attack:: " target_bssid

    if [[ ! "${target_bssid}" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
        echo "[Error] Invalid BSSID format. Please enter a valid MAC address (e.g., XX:XX:XX:XX:XX:XX)."
    else
        read -p "[fwifi] Enter the channel: " channel

        if [[ ! "$channel" =~ ^[0-9]+$ ]]; then
            echo "[Error] Invalid channel. Please enter a valid numeric channel."
        else
            besside-ng -b "${target_bssid}" -W -c "${channel}" -v "${interface}"
            echo ""
            read -p "[Info] Press [Enter] to continue..."
        fi
    fi
}

# Function to check for valid 4-way frames
check_4way_frames() {
    echo ""
    echo "[Info] Checking for valid 4-way frames..."
    echo ""
    aircrack-ng -w "${wordlist}" "${cap_file}"
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to crack Wi-Fi key
crack_wifi_key() {
    echo ""
    echo "[Menu] Choose Wi-Fi Key Cracking Tool"
    echo ""
    echo "[1] Aircrack-ng"
    echo "[2] Cowpatty"
    echo "[3] John The Ripper (John)"
    echo ""

    while true; do
        read -p "[fwifi] Enter your choice (1-3): " crack_tool

        case "${crack_tool}" in
            1) aircrack_crack ;;
            2) cowpatty_crack ;;
            3) john_crack ;;
            *) echo "[Error] Invalid choice." ;;
        esac
    done
}

# Function to crack Wi-Fi key using Aircrack-ng
aircrack_crack() {
    echo ""
    read -p "[fwifi] Enter the .cap file path: " cap_file
    echo ""
    read -p "[fwifi] Enter the wordlist file path: " wordlist
    echo ""
    aircrack-ng -w "${wordlist}" "${cap_file}"
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to crack Wi-Fi key using Cowpatty
cowpatty_crack() {
    echo ""
    read -p "[fwifi] Enter the .cap file path: " cap_file
    echo ""
    read -p "[fwifi] Enter the wordlist file path: " wordlist
    echo ""
    cowpatty -r "${cap_file}" -f "${wordlist}"
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to crack Wi-Fi key using John The Ripper (John)
john_crack() {
    echo ""
    read -p "[fwifi] Enter the .cap file path: " cap_file
    echo ""
    read -p "[fwifi] Enter the wordlist file path: " wordlist
    echo ""
    john --wordlist="${wordlist}" --format=wpapsk --rules --stdout | aircrack-ng -w - "${cap_file}"
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Function to exit the program
exit_program() {
    echo ""
    echo "[Info] Exiting FWIFI..."
    echo ""
    exit 0
}

# Function for invalid choice
invalid_choice() {
    echo ""
    echo "[Error] Invalid choice. Please select a valid option."
    echo ""
    read -p "[Info] Press [Enter] to continue..."
}

# Call the display intro function
display_intro

# Main program loop
while true; do
    main_menu
done
